### PR TITLE
Add to-do list for review

### PR DESCRIPTION
**Pull request by Stanleeeeee**
This is my to do list. It add, edit and delete tasks

### CODE REVIEW

**Comment by shahnawaza75** [comment]
Great Job,👍so far the project looks good. However, when I am trying to add something to the list it does not seem to be working.

**Comment by Stanleeeeee** [comment]
> Great Job,+1so far the project looks good. However, when I am trying to add something to the list it does not seem to be working.

Thank you very much for the review. Do you mean the live demo?

**Comment by Stanleeeeee** [comment]
I have been able to fix the link

**Comment by shahnawaza75** [comment]
@Stanleeeeee,
In my opinion, your project is complete! There is nothing else to say other than... it's time to merge it :

Good luck! 🎉

**Pull request merged**
